Ai pokemon jump
ionnikovv/training-ionnikov pull request #18
Opened 2021-11-02 13:33 UTC by ionnikovv

2021-11-02 15:10 UTC, mrlika commented on package.json
> +    "react-webcam": "^6.0.0",
As I see this dependency is not used

2021-11-02 15:21 UTC, mrlika requested changes

2021-11-02 15:21 UTC, mrlika commented on src/components/CameraComponent/Camera.tsx
> +    }
Refactor to use `async/await` instead of `then`

2021-11-02 15:21 UTC, mrlika commented on src/components/CameraComponent/Camera.tsx
> +    setVideoStream(await navigator.mediaDevices.getUserMedia(VIDEO_CONFIG));
Move this function into the hook that uses it

2021-11-02 16:40 UTC, mrlika requested changes

2021-11-02 16:40 UTC, mrlika commented on src/components/Game/Player/Player.tsx
> +  const webCameraElement = document.getElementById('webcamera');
Using `getElementById` in React application in most cases is wrong.

2021-11-02 16:44 UTC, mrlika requested changes

2021-11-02 16:44 UTC, mrlika commented on src/components/Game/Game.tsx
> +      document.dispatchEvent(setDownAI);
It is a bad way of passing events between components in React app. You should use callbacks.

2021-11-02 16:44 UTC, mrlika commented on src/components/CameraComponent/Camera.tsx
> +      {isCameraEnabled && <video ref={videoRef} id={'webcamera'} />}
Don't use `id` in HTML elements in React apps

2021-11-04 14:57 UTC, TheForsakenSpirit requested changes

2021-11-04 14:57 UTC, TheForsakenSpirit commented on src/ConstantValues/ConstValues.tsx
> +export const setUpAI = new Event('setUpAI');
is this steel required?

2021-11-04 14:57 UTC, TheForsakenSpirit commented on src/Hooks/useJumpAI.ts
> +};
custom hook that is function that use another hooks. Here I don't see any hooks.

Make useEffect and move to Game.tsx.

2021-11-04 14:57 UTC, TheForsakenSpirit commented on src/components/Game/Game.tsx
> +    }) ?? {};
hide this state of callbacks

2021-11-04 14:57 UTC, TheForsakenSpirit commented on src/components/Game/Game.tsx
> +  useJumpAi({ handleBack, handleJump, aiValue, isGameSessionStarted, paused, isCameraEnabled });
extract this function to useEffect

2021-11-04 16:57 UTC, mrlika requested changes

2021-11-05 10:46 UTC, TheForsakenSpirit requested changes

2021-11-05 10:46 UTC, TheForsakenSpirit commented on src/components/Game/Game.tsx
> +    if (aiValue <= -90) handleBack();
handleBack will be called two times

2021-11-05 10:46 UTC, TheForsakenSpirit commented on src/components/Game/Game.tsx
> +  const handleAiJump = (aiValue: number) => {
this call back used in useEffect, better to memorize with useCallback hook.

2021-11-07 15:03 UTC, mrlika requested changes

2021-11-07 15:03 UTC, mrlika commented on src/components/CameraComponent/Camera.tsx
> +      setDetector(null);
Setting `setDetector(null);` in cleanup function is wrong. If detector is changed by calling `setDetector(anotherDetector)` cleanup function will reset it to `null` that is wrong

2021-11-07 15:03 UTC, mrlika commented on src/components/CameraComponent/Camera.tsx
> +      {isCameraEnabled && <video ref={setVideoElement} />}
Looks like `isCameraEnabled` can be removed now

2021-11-23 08:52 UTC, mrlika approved these changes

2021-11-23 15:03 UTC, TheForsakenSpirit approved these changes

2021-11-23 16:11 UTC, merged