Handle loading state
ionnikovv/training-ionnikov pull request #6
Opened 2021-10-04 12:46 UTC by ionnikovv

In this branch was added handling of loading state

2021-10-05 13:34 UTC, TheForsakenSpirit approved these changes

2021-10-05 14:47 UTC, mrlika requested changes

2021-10-05 14:47 UTC, mrlika commented on src/components/PokemonCard/PokemonCard.tsx
>    const [isLoading, setIsLoading] = useState(true);
Set `isLoading` to `true` when loading started

2021-10-05 14:47 UTC, mrlika commented on src/components/PokemonCard/PokemonCard.tsx
> +    return (
Add curly brackets

2021-10-05 14:47 UTC, mrlika commented on src/App.tsx
> +const PAGE_SIZE = 1;
Leave `PAGE_SIZE = 10`

2021-10-05 14:47 UTC, mrlika commented on src/App.tsx
>    );
Don't export default: https://basarat.gitbook.io/typescript/main-1/defaultisbad

2021-10-05 14:47 UTC, mrlika commented on src/App.tsx
> +  const [lastPage, setLastPage] = useState(1);
Rename to `currentPage`

2021-10-05 14:47 UTC, mrlika commented on src/App.tsx
> +    if (lastPage === 0) return;
Remove this redundant check

2021-10-05 14:47 UTC, mrlika commented on src/App.tsx
> +  const [lastPage, setLastPage] = useState(1);
Leave counting pages from 0

2021-10-05 14:47 UTC, mrlika commented on src/App.tsx
> +        `https://pokeapi.co/api/v2/pokemon?limit=${PAGE_SIZE}&offset=${(lastPage - 1) * PAGE_SIZE}`
Don't change the line if counting from 0

2021-10-05 14:47 UTC, mrlika commented on src/App.tsx
> +        {isFetching && <Loader />}
Remove this line

2021-10-05 14:47 UTC, mrlika commented on package-lock.json
> +    "email-addresses": {
Remove this file

2021-10-06 10:38 UTC, mrlika approved these changes

2021-10-06 10:43 UTC, merged